import { createTRPCRouter } from "../../trpc";
import {
  findAllProject,
  findManyProjects,
  findManyReview,
  findManyVerified,
  findManyVerifiedUser,
  findOneJoinRound,
  findPubkey,
  findSimilar,
  searchProjects,
  updateProjectStatus,
  findOneProject,
  verifiedProjects,
  findManyRejected,
  findManyVerifiedWithContributions,
  projectVisitorsDetail,
  getProjects,
  findOneHackthon,
} from "./public";
import {
  createProject,
  joinRound,
  projectAdminDetails,
  projectCount,
  projectIsValid,
  projectsHackathonSubmit,
} from "./protected";
export const projectRouter = createTRPCRouter({
  findAll: findAllProject,
  findMany: findManyProjects,
  findManyReview: findManyReview,
  findManyVerified: findManyVerified,
  findPubkey: findPubkey,
  findManyRejected: findManyRejected,
  create: createProject,
  findManyVerifiedWithContributions: findManyVerifiedWithContributions,
  findOne: findOneProject,
  joinRound: joinRound,
  projectVisitorsDetail: projectVisitorsDetail,
  count: projectCount,
  updateProjectStatus: updateProjectStatus,
  verifiedProjects: verifiedProjects,
  findOneJoinRound: findOneJoinRound,
  findSimilarProjects: findSimilar,
  findManyVerifiedUser: findManyVerifiedUser,
  searchProjects: searchProjects,
  projectsHackathonSubmit: projectsHackathonSubmit,
  projectIsValid: projectIsValid,
  getProjects: getProjects,
  projectAdminDetails: projectAdminDetails,
  findOneHackthon: findOneHackthon,
});
