export const textStyles = {
  display: {
    xxl: {
      400: {
        fontSize: '72px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '90px',
        letterSpacing: '-1.44px',
      },
      500: {
        fontSize: '72px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '90px',
        letterSpacing: '-1.44px',
      },
      600: {
        fontSize: '72px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '90px',
        letterSpacing: '-1.44px',
      },
      700: {
        fontSize: '72px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '90px',
        letterSpacing: '-1.44px',
      },
    },
    xl: {
      400: {
        fontSize: '60px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '72px',
        letterSpacing: '-1.2px',
      },
      500: {
        fontSize: '60px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '72px',
        letterSpacing: '-1.2px',
      },
      600: {
        fontSize: '60px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '72px',
        letterSpacing: '-1.2px',
      },
      700: {
        fontSize: '60px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '72px',
        letterSpacing: '-1.2px',
      },
    },
    lg: {
      400: {
        fontSize: '48px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '60px',
        letterSpacing: '-0.96px',
      },
      500: {
        fontSize: '48px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '60px',
        letterSpacing: '-0.96px',
      },
      600: {
        fontSize: '48px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '60px',
        letterSpacing: '-0.96px',
      },
      700: {
        fontSize: '48px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '60px',
        letterSpacing: '-0.96px',
      },
    },
    md: {
      400: {
        fontSize: '36px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '44px',
        letterSpacing: '-0.72px',
      },
      500: {
        fontSize: '36px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '44px',
        letterSpacing: '-0.72px',
      },
      600: {
        fontSize: '36px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '44px',
        letterSpacing: '-0.72px',
      },
      700: {
        fontSize: '36px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '44px',
        letterSpacing: '-0.72px',
      },
    },
    sm: {
      400: {
        fontSize: '30px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '38px',
      },
      500: {
        fontSize: '30px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '38px',
      },
      600: {
        fontSize: '30px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '38px',
      },
      700: {
        fontSize: '30px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '38px',
      },
    },
    xs: {
      400: {
        fontSize: '24px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '32px',
      },
      500: {
        fontSize: '24px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '32px',
      },
      600: {
        fontSize: '24px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '32px',
      },
      700: {
        fontSize: '24px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '32px',
      },
    },
  },
  text: {
    xxl: {
      400: {
        fontSize: '22px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '30px',
      },
      500: {
        fontSize: '22px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '30px',
      },
      600: {
        fontSize: '22px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '30px',
      },
      700: {
        fontSize: '22px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '30px',
      },
    },
    xl: {
      400: {
        fontSize: '20px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '28px',
      },
      500: {
        fontSize: '20px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '28px',
      },
      600: {
        fontSize: '20px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '28px',
      },
      700: {
        fontSize: '20px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '28px',
      },
    },
    lg: {
      400: {
        fontSize: '18px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '26px',
      },
      500: {
        fontSize: '18px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '26px',
      },
      600: {
        fontSize: '18px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '26px',
      },
      700: {
        fontSize: '18px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '26px',
      },
    },
    md: {
      400: {
        fontSize: '16px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '24px',
      },
      500: {
        fontSize: '16px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '24px',
      },
      600: {
        fontSize: '16px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '24px',
      },
      700: {
        fontSize: '16px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '24px',
      },
    },
    sm: {
      400: {
        fontSize: '14px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '20px',
      },
      500: {
        fontSize: '14px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '20px',
      },
      600: {
        fontSize: '14px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '20px',
      },
      700: {
        fontSize: '14px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '20px',
      },
    },
    xs: {
      400: {
        fontSize: '12px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '18px',
      },
      500: {
        fontSize: '12px',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '18px',
      },
      600: {
        fontSize: '12px',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '18px',
      },
      700: {
        fontSize: '12px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '18px',
      },
    },
  },

  // ------- old styles -------
  display1: {
    fontSize: '56px',
    fontWeight: '700',
    lineHeight: '70px',
    letterSpacing: '-0.02em',
  },
  display2: {
    fontSize: '48px',
    fontWeight: '700',
    lineHeight: '60px',
    letterSpacing: '-0.02em',
  },
  display3: {
    fontSize: '40px',
    fontWeight: '700',
    lineHeight: '50px',
    letterSpacing: '-0.02em',
  },
  display4: {
    fontSize: '32px',
    fontWeight: '700',
    lineHeight: '40px',
    letterSpacing: '-0.02em',
  },
  display5: {
    fontSize: '28px',
    fontWeight: '700',
    lineHeight: '34px',
    letterSpacing: '-0.02em',
  },
  headline1: {
    fontSize: '36px',
    fontWeight: '700',
    lineHeight: '48px',
    letterSpacing: '-0.02em',
  },
  headline2: {
    fontSize: '32px',
    fontWeight: '700',
    lineHeight: '40px',
    letterSpacing: '-0.02em',
  },
  headline3: {
    fontSize: '28px',
    fontWeight: '700',
    lineHeight: '36px',
    letterSpacing: '-0.02em',
  },
  headline4: {
    fontSize: '24px',
    fontWeight: '700',
    lineHeight: '32px',
    letterSpacing: '-0.02em',
  },
  title1: {
    fontWeight: '700',
    fontSize: '24px',
    lineHeight: '32px',
  },
  title2: {
    fontWeight: '600',
    fontSize: '20px',
    lineHeight: '26px',
  },
  title3: {
    fontWeight: '600',
    fontSize: '18px',
    lineHeight: '24px',
  },
  title4: {
    fontWeight: '600',
    fontSize: '16px',
    lineHeight: '22px',
  },
  title5: {
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '18px',
  },
  title6: {
    fontWeight: '700',
    fontSize: '12px',
    lineHeight: '16px',
  },
  title7: {
    fontWeight: '500',
    fontSize: '11px',
    lineHeight: '14px',
  },
  title8: {
    fontWeight: '500',
    fontSize: '10px',
    lineHeight: '12px',
  },
  title9: {
    fontWeight: '400',
    fontSize: '9px',
    lineHeight: '10px',
  },
  overline1: {
    fontWeight: '700',
    fontSize: '16px',
    lineHeight: '20px',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
  },
  overline2: {
    fontWeight: '700',
    fontSize: '14px',
    lineHeight: '18px',
    letterSpacing: '0.2em',
    textTransform: 'uppercase',
  },
  overline3: {
    fontWeight: '600',
    fontSize: '10px',
    lineHeight: '12px',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
  },
  overline4: {
    fontWeight: '600',
    fontSize: '9px',
    lineHeight: '11px',
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
  },
  overline5: {
    fontWeight: '600',
    fontSize: '8px',
    lineHeight: '10px',
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
  },
  body1: {
    fontWeight: '400',
    fontSize: '24px',
    lineHeight: '32px',
  },
  body2: {
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '26px',
  },
  body3: {
    fontWeight: '400', //todo: confirm from designer
    fontSize: '16px',
    lineHeight: '24px',
  },
  body4: {
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
  },
  body5: {
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '18px',
  },
  body6: {
    fontWeight: '400',
    fontSize: '10px',
    lineHeight: '12px',
  },
  body7: {
    fontWeight: '400',
    fontSize: '8px',
    lineHeight: '10px',
  },
  // you can also use responsive styles
  //  fontSize: ['48px', '72px'],
};
