import SEO from '@/components/SEO';
import config from '@/config/general.config';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <SEO
        title={`${config.general.name}`}
        description={`${config.general.name} is a Quadratic funding platform on Solana Blockchain.`}
        image={`https://solana.ghost.io/content/images/2022/06/solana-network-upgrades.png`}
      />
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <footer></footer>
      </div>
    </>
  );
};

export default Home;
